name: CI
on: [push]
jobs:
  SmallNonHAMinrole-Binaries-SE:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Installing Prerequisites
        run: |
          Install-Module -Name Az -Force
          Install-Module -Name AutomatedLab -Force
