name: CI
on: [push]
jobs:
  SmallNonHAMinrole-Binaries-SE-Win2022:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Install Prerequisites
#        shell: powershell
        run: |
          .\InstallPrerequisites.ps1
      - name: Provision Lab
#        shell: powershell
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: |
          $securedPassword = ConvertTo-SecureString $env:ARM_CLIENT_SECRET -AsPlainText -Force;
          $azureCredential = New-Object System.Management.Automation.PSCredential( $env:ARM_CLIENT_ID, $securedPassword );
          Connect-AzAccount -Credential $azureCredential -ServicePrincipal -TenantId $env:ARM_TENANT_ID | Out-Null;
          Select-AzSubscription -SubscriptionId $env:ARM_SUBSCRIPTION_ID;
          .\DeploySharePointEnvironment.ps1
